- app/controllers/dilemmas_controller.rb
- app/views/dilemmas/index.html.erb
- app/views/dilemmas/new.html.erb
- app/views/dilemmas/show.html.erb
- config/routes.rb
Primitive version of Dilemmas controller
> Dilemmas controller

- app/controllers/replies_controller.rb
- app/views/replies/new.html.erb
- config/routes.rb
Iben, te mando el controller de Reply
> Controller for Reply

- app/controllers/dilemmas_controller.rb
- app/views/replies/new.html.erb
Iben,
Listo el controller para el dilemma con authorize
> Controller dilemma

- app/controllers/replies_controller.rb
Todo listo con el controller de Reply
> Reply controller

- app/assets/stylesheets/application.scss
- app/controllers/options_controller.rb
- app/views/dilemmas/index.html.erb
- template for the cards on the index page
> index dilemmas cards template

- .gitignore
- app/controllers/options_controller.rb
- app/policies/application_policy.rb
- app/policies/option_policy.rb
- app/views/dilemmas/show.html.erb
- config/routes.rb
- options policy added
- upvotes function added
- dilemma show page updated for option
> upvote downvote

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> Homepage css

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Updated the links for the homepage
> Listos los links

- app/assets/stylesheets/pages/_home.scss
- app/views/shared/_navbar.html.erb
> Listo con home

- app/assets/stylesheets/pages/_home.scss
> Listo el homepage

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Listo el Log in de la Nav Bar

- app/views/dilemmas/index.html.erb
> index link clickable

- app/assets/stylesheets/components/_card.scss
- app/views/dilemmas/index.html.erb
> css cleanup

- app/assets/stylesheets/components/_card.scss
- app/controllers/dilemmas_controller.rb
- app/controllers/replies_controller.rb
- app/models/dilemma.rb
- app/policies/reply_policy.rb
- app/views/dilemmas/show.html.erb
> Form for comments displays in the show page of dilemma but doesn't save

- .gitignore
The avatar for the user is ready for us to us it!
> Listo el avatar

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/controllers/dilemmas_controller.rb
- app/javascript/packs/application.js
- app/views/dilemmas/index.html.erb
- package.json
- yarn.lock
- chart kick poll added
- poll connection to upvotes
> polls added with counter

- app/assets/stylesheets/components/_button.scss
- app/controllers/dilemmas_controller.rb
- app/views/dilemmas/index.html.erb
> fixed button position on index

- app/views/pages/home.html.erb
Did the changes to the homepage
> The homepage is ready

- app/controllers/dilemmas_controller.rb
> Lista la search bar

- app/views/devise/registrations/new.html.erb
Did the changes Jolie told me!
> Lista la form

- app/views/dilemmas/index.html.erb
> button position

- app/views/devise/registrations/new.html.erb
- app/views/dilemmas/new.html.erb
- app/views/dilemmas/show.html.erb
Wording revision throughout site
> Typo cleanup

- app/views/dilemmas/show.html.erb
The expired_at is ready for the show page!
> The expired show is ready

- app/controllers/dilemmas_controller.rb
- app/views/dilemmas/show.html.erb
The show page for no logged in user is working
> repaired the show page

- app/mailers/user_mailer.rb
- app/models/user.rb
- app/views/user_mailer/welcome_email.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/devise.rb
- db/migrate/20200622191935_devise_create_users.rb
- test/mailers/previews/user_mailer_preview.rb
- test/mailers/user_mailer_test.rb
> confirmation email

- app/controllers/users_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/profile.html.erb
- config/routes.rb
- db/migrate/20200629205558_add_bio_to_users.rb
- db/schema.rb
> profile page created

- app/channels/dilemma_channel.rb
- app/controllers/replies_controller.rb
- app/javascript/channels/dilemma_channel.js
- app/javascript/packs/application.js
- app/views/dilemmas/_display-reply.html.erb
- app/views/dilemmas/show.html.erb
- app/views/replies/_display-replies.html.erb
- test/channels/dilemma_channel_test.rb
> Super facil action cable

- app/views/shared/_navbar.html.erb
> links in dropdown added

- app/models/dilemma.rb
- app/views/dilemmas/_display-reply.html.erb
- app/views/pages/home.html.erb
- app/views/replies/_display-replies.html.erb
> errors fixed

- app/assets/stylesheets/components/_index.scss
- app/views/dilemmas/index.html.erb
Arreglado! When you search for a non-existent dilemma it will return something really cool!
> Listo la searchbar

- app/assets/stylesheets/pages/_index.scss
> The scrollbar is ready

- app/assets/stylesheets/components/profile.scss
- app/views/dilemmas/index.html.erb
- app/views/users/profile.html.erb
> Profile 2nd section looks decent

- app/assets/stylesheets/pages/_index.scss
> Ya quedo lista la search bar

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
> The changes are ready

- app/assets/stylesheets/pages/_home.scss
> Did some minor changes

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/views/dilemmas/show.html.erb
- config/initializers/social_share_button.rb
> Social Media

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_share-button.scss
- app/javascript/packs/application.js
- app/views/dilemmas/show.html.erb
- package.json
- yarn.lock
The social media icons are ready!
> Add social icons project

- app/controllers/application_controller.rb
> Error Message
